### ISSUE TITLE
1.2.1 Yo como usuario administrador quiero que exista un formulario de registro que solicite solo el nombre de usuario y correo electrónico

### ISSUE THREAD

**Issue by vasquezed** [Camila1797/Trabajo-nfasis.#92]

**Comment by Camila1797** [comment]
- [ ] 1.2.1.1. Se almacenará la información por medio del correo electronico registrado.

- [ ] 1.2.1.2. el sistema permitirá inscribir los datos de manera voluntaria

- [ ] 1.2.1.3. El sistema sólo tendrá el correo, nickname y telefono como obligatorios.
