### ISSUE TITLE
4.1.3 yo como usuario quiero ver en el menú principal del juego un selector de los niveles

### ISSUE THREAD

**Issue by vasquezed** [Camila1797/Trabajo-nfasis.#93]

**Comment by Camila1797** [comment]
- [ ] 4.1.3.1 Crear interfaz de todos los niveles.
- [ ] 4.1.3.2 Mostrar todas las insignias que se pueden alcanzar.
- [ ] 4.1.3.3 Mostar las insignias logradas.
